"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const notifications_controller_1 = require("./notifications.controller");
const auth_1 = require("../../middlewares/auth");
const router = (0, express_1.Router)();
router.use(auth_1.authenticate);
router.get('/my', notifications_controller_1.NotificationsController.getMyNotifications);
router.patch('/:id/read', notifications_controller_1.NotificationsController.markAsRead);
exports.default = router;
