"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_controller_1 = require("./auth.controller");
const validate_1 = require("../../middlewares/validate");
const rate_limit_1 = require("../../middlewares/rate-limit");
const auth_1 = require("../../middlewares/auth");
const auth_validation_1 = require("./auth.validation");
const router = (0, express_1.Router)();
router.post('/register', rate_limit_1.authLimiter, (0, validate_1.validate)(auth_validation_1.registerSchema), auth_controller_1.AuthController.register);
router.post('/login', rate_limit_1.authLimiter, (0, validate_1.validate)(auth_validation_1.loginSchema), auth_controller_1.AuthController.login);
router.post('/refresh-token', (0, validate_1.validate)(auth_validation_1.refreshTokenSchema), auth_controller_1.AuthController.refreshToken);
router.post('/logout', auth_1.authenticate, auth_controller_1.AuthController.logout);
router.post('/forgot-password', (0, validate_1.validate)(auth_validation_1.forgotPasswordSchema), auth_controller_1.AuthController.forgotPassword);
router.post('/reset-password', (0, validate_1.validate)(auth_validation_1.resetPasswordSchema), auth_controller_1.AuthController.resetPassword);
router.get('/me', auth_1.authenticate, auth_controller_1.AuthController.me);
exports.default = router;
